version: 24.05-{build}
image:
- Visual Studio 2022
#- Visual Studio 2017
#- Visual Studio 2015
skip_tags: true

environment:
  matrix:
  #- src: official
  - src: zstd
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
build_script:
- cmd: >-
    7-zip-build.bat
test: off
skip_commits:
  files:
    - 'LICENSE'
    - '*.md'
    - '.gitingore'

#matrix:
#  allow_failures:
#    - image: Visual Studio 2017
#      src: zstd
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
